const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA';
const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR';
const FETCH_HEADER_DATA = 'FETCH_HEADER_DATA';
const FETCH_HEADER_ERROR = 'FETCH_HEADER_ERROR';
const FETCH_REQUESTED = 'FETCH_REQUESTED';
export {
    FETCH_SEARCH_DATA,
    FETCH_SEARCH_ERROR,
    FETCH_REQUESTED,
    FETCH_HEADER_DATA,
    FETCH_HEADER_ERROR,
}