version: '3'

services:

################################
#   Setup node container
################################
  server:
    # build: ./server
    build:
      context: ./server
      dockerfile: Dockerfile.server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      # - API_HOST: ${API_HOST}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/twitter-server/src
    env_file:
      - .env
    command: npm run dev

################################
#   Setup client container
################################
  # client:
  #   build: ./client
  #   environment:
  #     - REACT_APP_PORT=${REACT_APP_PORT}
  #     - APP_SERVER_PORT=${APP_SERVER_PORT}
  #     - REACT_
  #   expose:
  #     - ${REACT_APP_PORT}
  #   ports:
  #     - ${REACT_APP_PORT}:${REACT_APP_PORT}
  #   volumes:
  #     - ./client/src:/srv/app/twitter-client/src
  #     - ./client/public:/srv/app/twitter-client/public
  #   depends_on:
  #     - server 
  #   # links:
  #   #   - server
  #   command: npm run start
  web:
    # build: ./web
    build:
      context: ./web
      dockerfile: Dockerfile.web
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - REACT_
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./web/src:/srv/app/twitter-web/src
      - ./web/public:/srv/app/twitter-web/public
    depends_on:
      - server 
    # links:
    #   - server
    command: npm run start

  # server:
  #   build: .
  #   command: npm run start
